## Numpy Arrays

In [1]:
import numpy as np

In [2]:
myList = [1,2,3]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([1, 2, 3])

In [5]:
myList

[1, 2, 3]

In [15]:
myarr = np.array(myList) # convert list to numpy array by creating new variable

In [16]:
type(myarr)

numpy.ndarray

In [17]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [18]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0, 10, 2) # numpy range function 
# parameters : (start from 0, not including 10, step over 2 number)

array([0, 2, 4, 6, 8])

In [22]:
np.zeros(5) # indicating that 0. is just a floating numbers

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((5,5)) # 5 rows, 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.linspace(0,10,3)
# parameters : (start from 0, stop 10, total 3 numbers)

array([ 0.,  5., 10.])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(5,2) # random floating zero numbers

array([[0.83604782, 0.83319342],
       [0.68993643, 0.63064112],
       [0.27682443, 0.71613539],
       [0.53968604, 0.69285891],
       [0.73691272, 0.3952054 ]])

In [36]:
np.random.randn(10) # random floating real numbers

array([ 1.08239135, -1.96004171, -2.96461042,  0.52454134,  0.02090393,
       -0.11518891, -0.29041111,  1.35913353,  0.21585248, -0.08784657])

In [37]:
np.random.randn(2,3)

array([[ 1.51274786, -0.51185574, -0.66951558],
       [ 1.989372  ,  1.28764306, -0.64884112]])

In [40]:
np.random.randint(0,101,(4,5)) # random integers
# parameters : (start from 0, stop and not including 101,
# shape in matrix 4 rows and 5 columns)

array([[ 4,  9, 67, 34, 64],
       [ 5,  1, 71, 97, 65],
       [74, 47, 75,  4, 58],
       [87, 80, 71, 34, 51]])

In [41]:
np.random.randint(0,100,10)

array([26, 59,  7,  1, 19, 22, 28, 99, 66, 47])

In [43]:
np.random.seed(42) # arbitrary numbers to set particular set of numbers
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [46]:
np.random.seed(101) # it wont change, even we set it in random
np.random.rand(4) # look below

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [47]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [49]:
arr = np.arange(0, 25)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
arr.reshape(5,5) # reshaping the arr above into 5,5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
ranarr = np.random.randint(0,101,10)

In [54]:
ranarr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [55]:
ranarr.max() # return the maximum value of the array

92

In [57]:
ranarr.min() # return the minimum value of the array

4

In [58]:
ranarr.argmax() # return the index of maximum value

7

In [59]:
ranarr.argmin() # return the index of minimum value

3

In [60]:
ranarr.dtype # return the data type of the array

dtype('int64')

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
arr.shape # return the total arrays arr in rows and column shape

(25,)

In [63]:
arr = arr.reshape(5,5)

In [64]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
arr.shape

(5, 5)

In [67]:
arr.reshape(25,1) # 25 rows, 1 column

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [68]:
arr.reshape(1,25) # 1 rows, 25 column

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

---

### Coding Exercise Check- in: Creating NumPy Arrays

- **TASK**
    - Create a numpy array of 101 evely linearly spaced points between 0 and 10. Assign this array to a variable called myarray.

In [1]:
import numpy as np

In [2]:
myarray = np.linspace(0,10,101)

In [3]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])