In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11) # range from 0 to but not including 11

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8] # return the index

8

In [6]:
arr[1:5] # start from 1, but not including index 5

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5] # start from the beginning of the index but not including index 5

array([0, 1, 2, 3, 4])

In [9]:
arr[5:] # start from 5, till the end of the index

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100 # change the arr from the index 0 but not including index 5

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr[0:5]

In [18]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
slice_of_arr[:] = 99 # change all slice_of_arr index into 99
                     # and impacted on the arr index also

In [27]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [28]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [29]:
arr_copy = arr.copy()

In [30]:
arr_copy[:] = 100

In [32]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [33]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]]) #2 Dimension array

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d.shape

(3, 3)

In [36]:
arr_2d[0] # indexing from the 1st row in the line

array([ 5, 10, 15])

In [40]:
arr_2d[1,1] # return the 2nd row and the index 1

25

In [42]:
arr_2d[0,2]

15

In [44]:
arr_2d[:2] #return the matrix, except matrix in index 2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [45]:
arr_2d[:2,1:]
# return the matrix shape except matrix in index 2
# only shows the matrix in index 0 and 1, and only shown the shape of
# index 1 until index 2

array([[10, 15],
       [25, 30]])

In [46]:
arr = np.arange(1,11)

In [47]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr > 4 # return which array is bigger than 4 in boolean value

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
bool_arr = arr > 4 # create a new variable to input all value of array
                   # bigger than 4 which is true

In [50]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
arr[bool_arr] # reshape the boolean array into the integers

array([ 5,  6,  7,  8,  9, 10])

In [53]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

---

### Coding Exercise Check-in: Selecting Data from Numpy Array

- **TASK**
    - A six sided dice was rolled many times and the results of the rolls were saved to a numpy array called dice_rolls. How many times was a roll greater than 2 rolled? In other words, how many integers in the dice_rolls array are greater than 2? Assign your answer (should be an integer) to a variable called total_rolls_over_two.

In [54]:
import numpy as np

In [67]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [68]:
dice_rolls

array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6,
       3, 6, 2, 3, 5, 6, 5])

In [69]:
dice_rolls > 2

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [73]:
many_rolls = dice_rolls > 2

In [74]:
many_rolls

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [76]:
value = dice_rolls[many_rolls]

In [78]:
value

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [85]:
total_rolls_over_two = value.size

In [86]:
total_rolls_over_two

19