In [1]:
import numpy as np

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr + 5 # add every number in array with 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
arr - 2 # substract every number in array with 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [7]:
arr + arr # the array must be the same shape A + B = B + A

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr * arr # multiply every number in the array with array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr / arr # as we know that 0 / 0 is undefined

<ipython-input-10-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1 / arr

<ipython-input-11-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
np.sqrt(arr) # square root of each number in the array

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.sin(arr) # sines of each number in the array

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [14]:
np.log(arr) # logarithm number

<ipython-input-14-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [15]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr.sum() # sum of each number in the array

45

In [17]:
arr.mean() # mean of the array

4.5

In [18]:
arr.max()

9

In [19]:
arr.var() # variance

8.25

In [20]:
arr.std() # standard deviation

2.8722813232690143

In [24]:
arr2d = np.arange(0,25).reshape(5,5)

In [25]:
arr2d.shape

(5, 5)

In [26]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr2d.sum()

300

In [29]:
arr2d.sum(axis=0) # the sum across the rows
# ex; rows 1 = 0 + 5 + 10 + 15 + 20 = 50

array([50, 55, 60, 65, 70])

In [30]:
arr2d.sum(axis=1) # the sum across the columns
# ex; column 1 = 0 + 1 + 2 + 3 + 4 = 10

array([ 10,  35,  60,  85, 110])

In [31]:
# KEEP IN MIND THAT AXIS = 0 IS ROWS, AND AXIS = 1 IS COLUMN

---
### Coding Exercise Check-in : Operations on NumPy Array

- **TASK**
    - A bank account has had withdrawals and deposits tracked in a numpy array called account_transactions. Based on this list of account transactions, what is the total remaining in the account? Assign your answer to a variable called account_total.

In [32]:
import numpy as np

In [33]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [34]:
account_transactions

array([ 100, -200,  300, -400,  100,  100, -230,  450,  500, 2000])

In [35]:
account_transactions.size

10

In [36]:
account_transactions.reshape(2,5)

array([[ 100, -200,  300, -400,  100],
       [ 100, -230,  450,  500, 2000]])

In [37]:
account_transactions.sum()

2720